### ISSUE TITLE
Issues of deleted projects remain on the board

### ISSUE THREAD

**Issue by jakobbraun** [exasol/github-issue-adapter#8]
The board still shows issues of projects that were deleted / renamed.  For example the `project-keeper-maven-plugin` that was renamed to `project-keeper`.
Probably these issues are also aggregated into the total count.

**Comment by redcatbear** [comment]
If you look into our dashboard, you will see that there is at least one entry for `lua-coding` which is now called `lua-styleguide` 
![image](https://user-images.githubusercontent.com/584162/187834205-fc0e8765-c2cf-40f0-91bb-bdebf2997aca.png)

This is one of the cases where we have an artifact that is still associated with the old repo name.
